### ISSUE TITLE
Requisitos ligeiramente confusos

### ISSUE THREAD

**Issue by mracos** [stone-payments/tech-challenge#2]
Fala galera, sussa?
Então, ia puxar pra fazer (mesmo não estando ativamente atrás de uma vaga, queria algo pra aprender elixir haha) porém não entendi exatamente os requisitos. 😞 

Vi que tem ser rodado com `mix -S iex`, então seria meio que uma `lib`?
Ou uma aplicação em CLI?

Abraços! 😃

**Comment by gabrielgodoy** [comment]
Olá @mracos, 

Esse projeto em Elixir foi criado a partir da ferramenta Mix, que vem junto com o Elixir.

O comando `iex -S mix` serve para rodar a aplicação.

A forma como a aplicação vai ser desenvolvida fica a cargo do candidato, contanto que as premissas descritas nos casos de testes sejam cumpridas.

Abraço!

**Comment by mracos** [comment]
Beleza.
Obrigado!

**Comment by marcoonroad** [comment]
Na vdd é `iex -S mix run`. Partindo da suposição que nossos candidatos vão criar um Elixir Mix Application. No caso de um Phoenix Web Application, o comando seria `iex -S mix phx.server`. Não estamos cobrando que tipo de library ou framework nossos candidatos usem, se eles usarem uma dependência que starta de forma diferente do `mix run`, não tem problema, desde que esteja devidamente documentado como podemos testar/rodar o projeto, incluindo os passos necessários para configurá-lo.
